In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder

In [2]:
data = pd.read_csv('Social_Network_Ads.csv')
data.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
data.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [4]:
data.drop('User ID', axis=1, inplace=True)

In [5]:
label_encoder=LabelEncoder()
for col in data:
    data[col]=label_encoder.fit_transform(data[col])
print("Categorical DataFrame after Label Encoding:")
data.head()

Categorical DataFrame after Label Encoding:

   Gender  Age  EstimatedSalary  Purchased
0       1    1                4          0
1       1   17                5          0
2       0    8               26          0
3       0    9               39          0
4       1    1               57          0

In [6]:
X = data.drop('Purchased', axis=1)
y = data['Purchased']
y.head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    1
8    0
9    0
Name: Purchased, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30, random_state=42)
y_train.head()

157    0
109    0
17     1
347    1
24     1
Name: Purchased, dtype: int64

In [8]:
scaler= StandardScaler()
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
X_train = X_train_scaled 
X_train.head()

     Gender       Age  EstimatedSalary
0  1.021663 -0.842522         0.172613
1 -0.978796  0.041758         0.341605
2  1.021663  0.729530        -1.382113
3 -0.978796  1.613809         1.152767
4  1.021663  0.827784        -1.449710

In [9]:
scaler= StandardScaler()
X_test_scaled = pd.DataFrame(scaler.fit_transform(X_test), columns=X_test.columns)
X_test = X_test_scaled 
X_test.head()

    Gender       Age  EstimatedSalary
0 -0.98347  0.733726        -1.374943
1 -0.98347  1.902890         0.686640
2 -0.98347 -0.885118        -0.709916
3 -0.98347  0.913597         0.886148
4 -0.98347 -0.795182        -1.208686

In [10]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred_log = model.predict(X_test)

log_accuracy = accuracy_score(y_test, y_pred_log)
log_precision = precision_score(y_test, y_pred_log)
log_recall = recall_score(y_test, y_pred_log)
log_f1 = f1_score(y_test, y_pred_log)

print(f"Accuracy: {log_accuracy}")
print(f"Precision: {log_precision}")
print(f"Recall: {log_recall}")
print(f"F1 Score: {log_f1}")

Accuracy: 0.8416666666666667
Precision: 0.9375
Recall: 0.6382978723404256
F1 Score: 0.759493670886076

In [11]:
knn_sklearn = KNeighborsClassifier(n_neighbors=7)
knn_sklearn.fit(X_train, y_train)
y_pred_knn = knn_sklearn.predict(X_test)

knn_accuracy = accuracy_score(y_test, y_pred_knn)
knn_precision = precision_score(y_test, y_pred_knn)
knn_recall = recall_score(y_test, y_pred_knn)
knn_f1 = f1_score(y_test, y_pred_knn)

print(f"Accuracy: {knn_accuracy}")
print(f"Precision: {knn_precision}")
print(f"Recall: {knn_recall}")
print(f"F1 Score: {knn_f1}")

Accuracy: 0.925
Precision: 0.8958333333333334
Recall: 0.9148936170212766
F1 Score: 0.9052631578947369

In [12]:
svmclf = SVC(kernel='linear')
svmclf.fit(X_train, y_train)

y_pred_svmL = svmclf.predict(X_test)

In [13]:
svmL_accuracy = accuracy_score(y_test, y_pred_svmL)
svmL_precision = precision_score(y_test, y_pred_svmL)
svmL_recall = recall_score(y_test, y_pred_svmL)
svmL_f1 = f1_score(y_test, y_pred_svmL)

In [14]:
print(f"Accuracy: {svmL_accuracy}")
print(f"Precision: {svmL_precision}")
print(f"Recall: {svmL_recall}")
print(f"F1 Score: {svmL_f1}")

Accuracy: 0.825
Precision: 0.9642857142857143
Recall: 0.574468085106383
F1 Score: 0.7200000000000001

In [15]:
svmcpf = SVC(kernel='poly')
svmcpf.fit(X_train, y_train)

y_pred_svmP = svmcpf.predict(X_test)

In [16]:
svmP_accuracy = accuracy_score(y_test, y_pred_svmP)
svmP_precision = precision_score(y_test, y_pred_svmP)
svmP_recall = recall_score(y_test, y_pred_svmP)
svmP_f1 = f1_score(y_test, y_pred_svmP)

In [17]:
print(f"Accuracy: {svmP_accuracy}")
print(f"Precision: {svmP_precision}")
print(f"Recall: {svmP_recall}")
print(f"F1 Score: {svmP_f1}")

Accuracy: 0.8333333333333334
Precision: 0.9655172413793104
Recall: 0.5957446808510638
F1 Score: 0.7368421052631579

In [47]:
svmcrbf = SVC(kernel='rbf')
svmcrbf.fit(X_train, y_train)

y_pred_svmrbf = svmcrbf.predict(X_test)

In [49]:
svmRBF_accuracy = accuracy_score(y_test, y_pred_svmrbf)
svmRBF_precision = precision_score(y_test, y_pred_svmrbf)
svmRBF_recall = recall_score(y_test, y_pred_svmrbf)
svmRBF_f1 = f1_score(y_test, y_pred_svmrbf)

In [51]:
print(f"Accuracy: {svmRBF_accuracy}")
print(f"Precision: {svmRBF_precision}")
print(f"Recall: {svmRBF_recall}")
print(f"F1 Score: {svmRBF_f1}")

Accuracy: 0.9416666666666667
Precision: 0.9166666666666666
Recall: 0.9361702127659575
F1 Score: 0.9263157894736843

In [53]:
result_df = pd.DataFrame(columns=["Model", "Test Accuracy", "Test Precision","Test Recall","Test F1"])
result_df.loc[len(result_df)] = ["Logostic Regression", log_accuracy, log_precision, log_recall, log_f1]
result_df.loc[len(result_df)] = ["KNN", knn_accuracy, knn_precision, knn_recall, knn_f1]
result_df.loc[len(result_df)] = ["SVM Linear", svmL_accuracy, svmL_precision, svmL_recall, svmL_f1]
result_df.loc[len(result_df)] = ["SVM Poly", svmP_accuracy, svmP_precision, svmP_recall, svmP_f1]
result_df.loc[len(result_df)] = ["SVM RBF", svmRBF_accuracy, svmRBF_precision, svmRBF_recall, svmRBF_f1]
result_df

                 Model  Test Accuracy  Test Precision  Test Recall   Test F1
0  Logostic Regression       0.841667        0.937500     0.638298  0.759494
1                  KNN       0.925000        0.895833     0.914894  0.905263
2           SVM Linear       0.825000        0.964286     0.574468  0.720000
3             SVM Poly       0.833333        0.965517     0.595745  0.736842
4              SVM RBF       0.941667        0.916667     0.936170  0.926316

## SVM RBF IS THE BEST METRIC